#!/bin/bash
#Konstantin Zelmanovich
#Lab2 - Q11

if [ $# -ne 2 ]; then
	echo "Please enter 2 extensions, first old, then new"
	exit 1
fi

for i in *$1; do
	mv "$i" "${i/%$1/$2}" 
		if [ $? -ne 0 ]; then
			echo "Can not move file $i." 
		fi
done
